### ISSUE TITLE
1.16.2 issue

### ISSUE THREAD

**Issue by Xinoms** [nathandstory/Medallion-of-Flight#1]
Just updated my server to 1.16.2 and the plugin has stopped working, would really appreciate this being looked into as it’s used a lot on the server by my members.

**Comment by nathandstory** [comment]
> Just updated my server to 1.16.2 and the plugin has stopped working, would really appreciate this being looked into as it’s used a lot on the server by my members.

Wow that is awesome to hear, I didn't know it was being used much. Let me get my dev environment setup again and I'll get it updated for you all.

**Comment by nathandstory** [comment]
> Just updated my server to 1.16.2 and the plugin has stopped working, would really appreciate this being looked into as it’s used a lot on the server by my members.

I have updated it to 1.16.2 and tested it on my 1.16.2 server, should be good to go now. Let me know if you find any bugs.

https://www.spigotmc.org/resources/medallion-of-flight.71290/
